### ISSUE TITLE
Optional commands arguments are not working for Console Commands

### ISSUE THREAD

**Issue by Guthen** [Erlite/Advisor#27]
Module : `framework/commandhandler`

When running the command from the console, defaults value from Optional Arguments are not passed in the Command Callback. Instead the parser of the argument is executed. However, this is working when running the command from chat.

Consider this example :
![image](https://user-images.githubusercontent.com/33220603/137624264-adf1096c-86ea-4412-ba22-30cca2e93e5a.png)
![image](https://user-images.githubusercontent.com/33220603/137624273-f78c8e86-3792-4f1b-914d-f868ef3340b9.png)

**Comment by Erlite** [comment]
It's yours
