### ISSUE TITLE
Add font scaling client convar (50% -> 200% font size slider)

### ISSUE THREAD

**Issue by Erlite** [Erlite/Advisor#30]
- [ ] Add a `advisor_text_scale` convar, takes a number between 0.5 and 2
- [ ] Create a `Advisor.NumSlider` UI element with the same style as the others. Derives from `DNumSlider`
- [ ] Create the `Settings` menu page. For now, only add the text scale setting.
- [ ] Call the font update function in `cl_fonts` when the value is changed.

This will allow users to scale the font according to their screen's pixel density. Resolution scaling alone won't give us a "perfect" result.

**Comment by Lexa013** [comment]
I claim it

**Comment by Erlite** [comment]
Up for grabs.

**Comment by Guthen** [comment]
I'm currently on it
