### ISSUE TITLE
Problem with text size

### ISSUE THREAD

**Issue by Lexa013** [Erlite/Advisor#32]
When im resizing the font all of the next becomes buggy

![image](https://user-images.githubusercontent.com/48451588/137648744-9804de28-da6a-46fd-ab72-57f1830f0b01.png)

**Comment by Lexa013** [comment]
Same issue in big mode 
![image](https://user-images.githubusercontent.com/48451588/137648775-a27deb3a-812f-49f2-96d0-074ac012004b.png)

**Comment by Erlite** [comment]
The issue you're talking about is on a branch you're currently working on. The branch has not been merged, and is awaiting changes.

In that case, it's your responsibility to implement those fixes as the issue comes from what you're working on.
